doctrine:
    dbal:
#        url: '%env(DATABASE_URL)%'
        host: '%env(string:default:placeholder:DATABASE_HOST)%'
        dbname: '%env(string:default:placeholder:DATABASE_NAME)%'
        user: '%env(string:default:placeholder:DATABASE_USER)%'
        password: '%env(string:default:placeholder:DATABASE_PASSWORD)%'
        port: '%env(string:DATABASE_PORT)%'
        server_version: '%env(string:DATABASE_SERVER_VERSION)%'
        driver: '%env(string:DATABASE_DRIVER)%'

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/App/Entity'
                prefix: 'App\Entity'
                alias: App

#when@test:
#    doctrine:
#        dbal:
#            # "TEST_TOKEN" is typically set by ParaTest
#            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
