apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app.kubernetes.io/name: php
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: php-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: php-app
    spec:
      # Comment next line if you don't want to use GCP Secret Manager
      serviceAccountName: {{ .Values.app_k8_service_account_name }}
      containers:
        - name: php
          image: {{ .Values.image.repository }}/{{.Chart.Name}}/php
          ports:
            - containerPort: 9000
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "bin/postdeploy.sh"]
