services:
  nginx:
    extends:
      file: common-services.yaml
      service: nginx
    container_name: ${COMPOSE_PROJECT_NAME:-symfony-react-skeleton}_nginx_prod
    build:
      target: deployment
    image: ${COMPOSE_PROJECT_NAME:-symfony-react-skeleton}_nginx_prod:1.25-alpine

  php:
    extends:
      file: common-services.yaml
      service: php
    container_name: ${COMPOSE_PROJECT_NAME:-symfony-react-skeleton}_php_prod
    build:
      target: deployment
      args:
        - symfony_mode=prod
    image: ${COMPOSE_PROJECT_NAME:-symfony-react-skeleton}_php_prod:8.2-fpm-alpine
    environment:
      DATABASE_HOST: mysql
      DATABASE_SERVER_VERSION: 8.0.33
      DATABASE_PORT: 3306
      DATABASE_NAME: develop
      DATABASE_USER: develop
      DATABASE_PASSWORD: develop
      DATABASE_ROOT_PASSWORD: root

networks:
  public:
    name: ${COMPOSE_PROJECT_NAME:-symfony-react-skeleton}_public
    external: true
  backend:
    name: ${COMPOSE_PROJECT_NAME:-symfony-react-skeleton}_backend
    external: true
