services:
  nginx:
    extends:
      file: common-services.yaml
      service: nginx
    container_name: startup-helper_nginx
    build:
      target: base
    image: startup-helper_nginx:1.25-alpine
    ports:
      - "81:8080"
    volumes:
      - ../fe/dist:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  php:
    extends:
      file: common-services.yaml
      service: php
    container_name: startup-helper_php
    build:
      target: local
      args:
        - symfony_mode=dev
    image: startup-helper_php:8.2-fpm-alpine
    volumes:
      - ../api:/var/www/html

  postgres:
    container_name: startup-helper_postgres
    image: postgres:${DATABASE_SERVER_VERSION:-15.3}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DATABASE: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT:-5432}:${DATABASE_PORT:-5432}
    networks:
      - backend

networks:
  public:
    name: startup-helper_public
  backend:
    name: startup-helper_backend

volumes:
  postgres-data:
    name: startup-helper_postgresql-data