services:
  nginx:
    extends:
      file: common-services.yaml
      service: nginx
    container_name: ${COMPOSE_PROJECT_NAME:-symfony-react-skeleton}_nginx
    build:
      target: base
    image: ${COMPOSE_PROJECT_NAME:-symfony-react-skeleton}_nginx:1.25-alpine
    volumes:
      - ../api/public:/var/www/html/public
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  php:
    extends:
      file: common-services.yaml
      service: php
    container_name: ${COMPOSE_PROJECT_NAME:-symfony-react-skeleton}_php
    build:
      target: local
      args:
        - symfony_mode=dev
    image: ${COMPOSE_PROJECT_NAME:-symfony-react-skeleton}_php:8.2-fpm-alpine
    volumes:
      - ../api:/var/www/html

  postgres:
    container_name: ${COMPOSE_PROJECT_NAME:-symfony-react-skeleton}_postgres
    image: postgres:${DATABASE_SERVER_VERSION:-8}
    volumes:
      - postgres-data:/var/lib/mysql
    environment:
      POSTGRES_DATABASE: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    networks:
      - backend

networks:
  public:
    name: ${COMPOSE_PROJECT_NAME:-symfony-react-skeleton}_public
  backend:
    name: ${COMPOSE_PROJECT_NAME:-symfony-react-skeleton}_backend

volumes:
  postgres-data:
    name: ${COMPOSE_PROJECT_NAME:-symfony-react-skeleton}_mysql-data
