on:
  workflow_call:

jobs:
  lint:
    runs-on: self-hosted
    name: Lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: helm lint
        run: |
          cd .deploy && helm lint --strict --with-subcharts

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Run chart-testing (lint)
        run: ct lint --all --target-branch ${{ github.event.repository.default_branch }} --chart-dirs .deploy --check-version-increment false

      - name: List changed charts
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }} --chart-dirs .deploy)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create kind cluster
#        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.4.0

      - name: Run chart-testing (install)
#        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --all --target-branch ${{ github.event.repository.default_branch }} --chart-dirs .deploy
